[2025-04-06T11:37:09.187+0000] {processor.py:157} INFO - Started process (PID=85) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:37:09.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:37:09.192+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:37:09.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:37:09.232+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:37:09.214+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:37:09.233+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:37:09.280+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.101 seconds
[2025-04-06T11:37:39.788+0000] {processor.py:157} INFO - Started process (PID=89) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:37:39.791+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:37:39.793+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:37:39.792+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:37:39.813+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:37:39.809+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:37:39.818+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:37:39.899+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.117 seconds
[2025-04-06T11:38:10.060+0000] {processor.py:157} INFO - Started process (PID=93) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:38:10.140+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:38:10.143+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:38:10.142+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:38:10.170+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:38:10.164+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:38:10.172+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:38:10.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.183 seconds
[2025-04-06T11:38:40.701+0000] {processor.py:157} INFO - Started process (PID=97) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:38:40.767+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:38:40.770+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:38:40.770+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:38:40.827+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:38:40.823+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:38:40.828+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:38:40.969+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.280 seconds
[2025-04-06T11:39:11.527+0000] {processor.py:157} INFO - Started process (PID=101) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:39:11.533+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:39:11.537+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:39:11.536+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:39:11.581+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:39:11.577+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:39:11.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:39:11.720+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.207 seconds
[2025-04-06T11:39:41.882+0000] {processor.py:157} INFO - Started process (PID=105) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:39:41.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:39:41.886+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:39:41.885+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:39:41.899+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:39:41.897+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:39:41.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:39:41.939+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.063 seconds
[2025-04-06T11:40:12.793+0000] {processor.py:157} INFO - Started process (PID=109) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:40:12.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:40:12.798+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:40:12.797+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:40:12.812+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:40:12.809+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:40:12.813+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:40:12.928+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.142 seconds
[2025-04-06T11:40:43.596+0000] {processor.py:157} INFO - Started process (PID=113) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:40:43.599+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:40:43.602+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:40:43.601+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:40:43.621+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:40:43.618+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:40:43.623+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:40:43.687+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.100 seconds
[2025-04-06T11:41:14.873+0000] {processor.py:157} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:14.887+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:41:14.891+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:41:14.889+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:14.946+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:41:14.939+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:41:14.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:15.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.197 seconds
[2025-04-06T11:41:27.381+0000] {processor.py:157} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:27.383+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:41:27.391+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:41:27.390+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:27.440+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:41:27.433+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:41:27.442+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:27.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.148 seconds
[2025-04-06T11:41:57.781+0000] {processor.py:157} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:57.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:41:57.824+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:41:57.812+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:57.878+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:41:57.872+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:41:57.882+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:41:57.971+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.226 seconds
[2025-04-06T11:43:52.249+0000] {processor.py:157} INFO - Started process (PID=31) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:43:52.295+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:43:52.494+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:43:52.466+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:43:52.563+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:43:52.545+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:43:52.587+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:43:52.824+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.830 seconds
[2025-04-06T11:44:23.574+0000] {processor.py:157} INFO - Started process (PID=33) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:44:23.623+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:44:23.816+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:44:23.808+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:44:23.961+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:44:23.918+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:44:23.971+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:44:24.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 1.133 seconds
[2025-04-06T11:44:54.952+0000] {processor.py:157} INFO - Started process (PID=36) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:44:54.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:44:54.966+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:44:54.965+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:44:55.020+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:44:55.006+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:44:55.021+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:44:55.198+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.254 seconds
[2025-04-06T11:45:25.562+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:45:25.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:45:25.647+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:45:25.639+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:45:25.763+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:45:25.750+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:45:25.768+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:45:25.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.332 seconds
[2025-04-06T11:45:56.172+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:45:56.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:45:56.186+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:45:56.185+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:45:56.205+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:45:56.201+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:45:56.207+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:45:56.250+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.088 seconds
[2025-04-06T11:46:26.577+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:46:26.580+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:46:26.587+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:46:26.586+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:46:26.602+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:46:26.599+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:46:26.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:46:26.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.091 seconds
[2025-04-06T11:46:57.012+0000] {processor.py:157} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:46:57.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:46:57.029+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:46:57.028+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:46:57.052+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:46:57.048+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:46:57.056+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:46:57.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.110 seconds
[2025-04-06T11:47:27.544+0000] {processor.py:157} INFO - Started process (PID=56) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:47:27.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:47:27.556+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:47:27.556+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:47:27.576+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:47:27.572+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:47:27.580+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:47:27.631+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.097 seconds
[2025-04-06T11:47:58.216+0000] {processor.py:157} INFO - Started process (PID=60) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:47:58.246+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:47:58.261+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:47:58.261+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:47:58.388+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:47:58.376+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:47:58.390+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:47:58.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.449 seconds
[2025-04-06T11:48:20.085+0000] {processor.py:157} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:48:20.089+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:48:20.095+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:48:20.095+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:48:20.118+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:48:20.114+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:48:20.121+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:48:20.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.104 seconds
[2025-04-06T11:50:25.416+0000] {processor.py:157} INFO - Started process (PID=28) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:50:25.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:50:25.442+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:50:25.442+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:50:25.491+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:50:25.483+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:50:25.504+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:50:25.745+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.347 seconds
[2025-04-06T11:50:55.879+0000] {processor.py:157} INFO - Started process (PID=32) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:50:55.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:50:55.899+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:50:55.898+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:50:55.925+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:50:55.920+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:50:55.927+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:50:56.006+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.147 seconds
[2025-04-06T11:51:26.327+0000] {processor.py:157} INFO - Started process (PID=36) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:51:26.341+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:51:26.361+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:51:26.360+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:51:26.403+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:51:26.399+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:51:26.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:51:26.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.222 seconds
[2025-04-06T11:51:57.521+0000] {processor.py:157} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:51:57.530+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:51:57.540+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:51:57.539+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:51:57.599+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:51:57.588+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:51:57.600+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:51:57.665+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.155 seconds
[2025-04-06T11:52:27.936+0000] {processor.py:157} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:52:27.941+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:52:27.950+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:52:27.949+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:52:27.972+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:52:27.967+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:52:27.973+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:52:28.056+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.132 seconds
[2025-04-06T11:52:58.441+0000] {processor.py:157} INFO - Started process (PID=48) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:52:58.448+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:52:58.454+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:52:58.454+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:52:58.478+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:52:58.474+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/dag_forvenue.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_forvenue.py", line 10, in <module>
    from API_FORVENUE import main as run_forvenue
ModuleNotFoundError: No module named 'API_FORVENUE'
[2025-04-06T11:52:58.479+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:52:58.534+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/dag_forvenue.py took 0.111 seconds
[2025-04-06T11:53:28.701+0000] {processor.py:157} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_forvenue.py
[2025-04-06T11:53:28.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/dag_forvenue.py for tasks to queue
[2025-04-06T11:53:28.743+0000] {logging_mixin.py:151} INFO - [2025-04-06T11:53:28.741+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/dag_forvenue.py
